dist:
  xenial
sudo:
  false

language:
  cpp
os:
  - osx
# Linux builds are disabled until xenial ships with CMake 3.13
#  - linux

compiler:
  - gcc
  - clang

before_script:
  - mkdir build && cd build
  - cmake ..

script:
  - cmake --build .
  - ctest .